version: '3.9'
name: spring-boot-keycloak-from-scratch

services:

  keycloak-db:
    container_name: keycloak-db
    hostname: keycloak-db
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_KEYCLOAK_DB_DATABASE}
      MYSQL_USER: ${MYSQL_KEYCLOAK_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_KEYCLOAK_DB_PASSWORD}
    expose:
      - 3306
    volumes:
      - keycloak-db-volume:/var/lib/mysql
      - keycloak-db-volume:/docker-entrypoint-initdb.d
    networks:
      - spring-boot-keycloak-from-scratch
    restart: unless-stopped

  keycloak:
    depends_on:
      - keycloak-db
    hostname: keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    environment:
      DB_VENDOR: mysql
      DB_ADDR: keycloak-db
      DB_DATABASE: ${MYSQL_KEYCLOAK_DB_DATABASE}
      DB_USER: ${MYSQL_KEYCLOAK_DB_USER}
      DB_SCHEMA: ${MYSQL_KEYCLOAK_DB_DATABASE}
      DB_PASSWORD: ${MYSQL_KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    expose:
      - 8080
      - 8443
    ports:
      - "8000:8080"
      - "8443:8443"
    restart: unless-stopped
    command: start-dev --http-relative-path /
    networks:
      - spring-boot-keycloak-from-scratch

  customer-api-db:
    container_name: customer-api-db
    hostname: customer-api-db
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CUSTOMER_API_DB_DATABASE}
      MYSQL_USER: ${MYSQL_CUSTOMER_API_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_CUSTOMER_API_DB_PASSWORD}
    expose:
      - 3306
    volumes:
      - customer-api-db:/var/lib/mysql
      - customer-api-db:/docker-entrypoint-initdb.d
    networks:
      - spring-boot-keycloak-from-scratch

  customer-api:
    container_name: customer-api
    hostname: customer-api
    depends_on:
      - customer-api-db
    build: .
    environment:
      MYSQL_HOST: customer-api-db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_CUSTOMER_API_DB_DATABASE}
      MYSQL_USER: ${MYSQL_CUSTOMER_API_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_CUSTOMER_API_DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - spring-boot-keycloak-from-scratch

volumes:
  keycloak-db-volume:
    driver: local
  customer-api-db:
    driver: local

networks:
  spring-boot-keycloak-from-scratch:
    driver: bridge